---
- name: Automated Teaming Setup
  hosts: rhel1
  become: true
  become_method: sudo
  vars_files:
    - “{{ playbook_dir }}/vars/rhel1_team_vars.yml”

  vars:
    network_connections:
      - name: “{{ team_name }}”
        state: up
        type: team
        interface_name: “{{ team_name }}”
        ip:
          address:
            - “{{ ipv4_team_address }}”
            - “{{ ipv6_team_address }}”

      - name: member1
        state: up
        type: ethernet
        interface_name: “{{ int1 }}”
        controller: “{{ team_name }}”

      - name: member2
        state: up
        type: ethernet
        interface_name: “{{ int2 }}”
        controller: “{{ team_name }}”

  roles:
    - rhel-system-roles.network