---
- name: MariaDB install and configuration
  hosts: mariadb_servers
  become: true
  become_method: sudo

  tasks:
    - name: Install MariaDB server
      package:
        name: '@mariadb:10.3/server'
        state: present

    - name: Install MariaDB client
      package:
        name: mariadb
        state: latest

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Open firewall rules for MariaDB
      firewalld:
        service: mysql
        permanent: true
        state: enabled

    - name: Reload firewall
      command:
        cmd: firewall-cmd --reload

    - name: Install PyMySQL
      package:
        name: python3-PyMySQL
        state: present

    - name: Set root password for MariaDB
      mysql_user:
        name: root
        host_all: true
        update_password: always
        password: redhat
      no_log: true
      ignore_errors: true

    - name: Copy user and password to home
      copy:
        src: "{{ playbook_dir }}/my.cnf"
        dest: /root/.my.cnf

    - name: Delete anonymous user
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Add employees database
      mysql_db:
        name: employees
        state: present
        config_file: /root/.my.cnf

    - name: Copy insert.sql file to tmp
      copy:
        src: "{{ playbook_dir }}/insert.sql"
        dest: /tmp/insert.sql

    - name: Import the insert.sql information into the database
      mysql_db:
        name: employees
        state: import
        target: /tmp/insert.sql
        config_file: /root/.my.cnf

    - name: Add user
      mysql_user:
        name: david
        password: redhat
        update_password: on_create
        state: present
      no_log: true

    - name: Provide user with privileges
      mysql_user:
        name: david
        host: localhost
        priv: 'people.*:INSERT,UPDATE,SELECT'
        state: present
