---
- name: Install and Configure DHCP Server
  hosts: dhcp_servers
  become: true
  become_method: sudo

  tasks:
    - name: Install dhcp-server package
      package:
        name: dhcp-server
        state: latest

    - name: Set subnet configuration of DHCP-Server
      template:
        src: “{{ playbook_dir }}/templates/dhcpd.conf.j2”
        dest: /etc/dhcp/dhcpd.conf

    - name: Enable and start dhcp-server service
      service:
        name: dhcpd
        enabled: true
        state: restarted

    - name: Open firewall rules
      firewalld:
        permanent: true
        immediate: true
        service: dhcp
        state: enabled