---
- name: DNS server playbook
  hosts: rhel1.example.com
  become: true
  become_method: sudo

  tasks:
    - name: Install dns service
      package:
        name: bind
        state: latest

    - name: Copy dns main config
      template:
        src: "{{ playbook_dir }}/named.conf.j2"
        dest: /etc/named.conf

    - name: Copy dns forward zone configs
      template:
        src: "{{ playbook_dir }}/example.com.zone.j2"
        dest: /var/named/example.com.zone

    - name: Copy dns reverse zone configs
      template:
        src: "{{ playbook_dir }}/1.168.192.zone.j2"
        dest: /var/named/1.168.192.zone

    - name: Start and enable DNS
      service:
        name: named
        state: restarted
        enabled: true

    - name: Enable DNS firewall rule
      command:
        cmd: firewall-cmd --permanent --add-service=dns

    - name: Reload firewall
      command:
        cmd: firewall-cmd --reload

    - name: Install DIG to check configuration
      package:
        name: bind-utils
        state: latest

    - name: Run dig to test configuration
      command:
        cmd: "dig rhel2.example.com @192.168.1.198"